FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef
WORKDIR /usr/src/mcs

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /usr/src/mcs/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release -p lb

FROM debian:trixie-slim AS runtime
WORKDIR /app
COPY --from=builder /usr/src/mcs/target/release/lb /usr/local/bin
EXPOSE 64400
ENTRYPOINT ["/usr/local/bin/lb"]
